
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MEMBER;
DROP TABLE "TEACHER" CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_TEACJER;
DROP TABLE "BIRTHDAY" CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BIRTHDAY;
DROP TABLE "PROFILE_PHOTO" CASCADE CONSTRAINTS;
DROP SEQUENCE PROFILE_PHOTO;
DROP TABLE "EMAIL" CASCADE CONSTRAINTS;
DROP SEQUENCE EMAIL;
DROP TABLE "BLACKLIST" CASCADE CONSTRAINTS;
DROP SEQUENCE BLACKLIST;
DROP TABLE "ADMIN" CASCADE CONSTRAINTS;
DROP TABLE "SNS" CASCADE CONSTRAINTS;

DROP TABLE "TOP_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "MID_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "SECTION" CASCADE CONSTRAINTS;
DROP TABLE "SUB_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "MOVIE" CASCADE CONSTRAINTS;
DROP TABLE "VIDEO" CASCADE CONSTRAINTS;

DROP TABLE "GOAL" CASCADE CONSTRAINTS;
DROP TABLE "REQUIREMENT" CASCADE CONSTRAINTS;
DROP TABLE "SUBJECT" CASCADE CONSTRAINTS;
DROP TABLE "CART" CASCADE CONSTRAINTS;
DROP TABLE "WISH" CASCADE CONSTRAINTS;
DROP TABLE "ORDER_SUMMARY" CASCADE CONSTRAINTS;
DROP TABLE "PAYMENT" CASCADE CONSTRAINTS;
DROP TABLE "PAYSTATE" CASCADE CONSTRAINTS;
DROP TABLE "REVIEW" CASCADE CONSTRAINTS;
DROP TABLE "ADMINBOARD" CASCADE CONSTRAINTS;
DROP TABLE "TARGET" CASCADE CONSTRAINTS;

DROP TABLE "TEACHERBOARD" CASCADE CONSTRAINTS;
DROP TABLE "MESSAGE" CASCADE CONSTRAINTS;
DROP TABLE "ORDER_DETAIL" CASCADE CONSTRAINTS;
DROP TABLE "DISCOUNT_LOG" CASCADE CONSTRAINTS;
DROP TABLE "CHARGE" CASCADE CONSTRAINTS;
DROP TABLE "POINT_LOG" CASCADE CONSTRAINTS;
DROP TABLE "POINT" CASCADE CONSTRAINTS;
DROP TABLE "CHAT" CASCADE CONSTRAINTS;

SELECT 'DROP SEQUENCE "' || SEQUENCE_NAME|| '" CASCADE CONSTRAINTS;' FROM user_sequences;

DROP SEQUENCE "SEQ_ADMIN"  ;
DROP SEQUENCE "SEQ_ADMINBOARD"  ;
DROP SEQUENCE "SEQ_BLACKLIST"  ;
DROP SEQUENCE "SEQ_CART"  ;
DROP SEQUENCE "SEQ_CHARGE"  ;
DROP SEQUENCE "SEQ_CHAT"  ;
DROP SEQUENCE "SEQ_DISCOUNT_LOG"  ;
DROP SEQUENCE "SEQ_EMAIL"  ;
DROP SEQUENCE "SEQ_GOAL"  ;
DROP SEQUENCE "SEQ_MESSAGE"  ;
DROP SEQUENCE "SEQ_MID_CATEGORY"  ;

DROP SEQUENCE "SEQ_MOVIE"  ;
DROP SEQUENCE "SEQ_ORDER_DETAIL"  ;
DROP SEQUENCE "SEQ_ORDER_SUMMARY"  ;
DROP SEQUENCE "SEQ_PAYMENT"  ;
DROP SEQUENCE "SEQ_PAYSTATE"  ;
DROP SEQUENCE "SEQ_POINT"  ;
DROP SEQUENCE "SEQ_POINT_LOG"  ;
DROP SEQUENCE "SEQ_PROFILEPHOTO"  ;
DROP SEQUENCE "SEQ_PROFILE_PHOTO"  ;
DROP SEQUENCE "SEQ_REQUIREMENT"  ;
DROP SEQUENCE "SEQ_REVIEW"  ;

DROP SEQUENCE "SEQ_SECTION"  ;
DROP SEQUENCE "SEQ_SNS"  ;
DROP SEQUENCE "SEQ_SNS_NAME"  ;
DROP SEQUENCE "SEQ_SUBJECT"  ;
DROP SEQUENCE "SEQ_SUB_CATEGORY"  ;
DROP SEQUENCE "SEQ_TARGET"  ;
DROP SEQUENCE "SEQ_TEACHER"  ;
DROP SEQUENCE "SEQ_TEACHERBOARD"  ;
DROP SEQUENCE "SEQ_TOP_CATEGORY"  ;
DROP SEQUENCE "SEQ_VIDEO";
DROP SEQUENCE "SEQ_WISH";

